GET http://localhost:8000/api/users HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY0NTgyMjYwLCJleHAiOjE2NjQ1ODQwNjB9.1D43v_jlyElIYH4cD_iYTsKrpvB0L_bSa6ioO7xJfVM
##

###
POST http://localhost:8000/api/users HTTP/1.1
content-type: application/json

{
    "name": "Usuario4" ,
    "email": "usuario4@gmail.com",
    "nick": "nick4",
    "password": "12345678",
    "address": "Rua 4",
    "num": "1234",
    "complement": "Casa 4",
    "city": "Fortaleza",
    "state": "CE",
    "district": "Bairro4",
    "birth_date": "31-12-1985",
    "zip": "60860-000",
    "phone": "(85) 98888-9999"
}

###

GET http://localhost:8000/api/users/nick/nick1 HTTP/1.1

###
GET http://localhost:8000/api/users/nick/nick2 HTTP/1.1

###
POST http://localhost:8000/api/users/login HTTP/1.1
content-type: application/json

{ 
    "email": "alvaromartinezferreira@gmail.com",
    "pwd": "alvaro125"
}

###
PUT http://192.168.15.15:8000/api/users/pwd/1 HTTP/1.1
content-type: application/json

{ 
    "pwd": "pwd3"
}
###
GET http://localhost:8000/api/users/5 HTTP/1.1

###
PUT http://192.168.15.15:8000/api/users/1 HTTP/1.1
content-type: application/json

{
    "name": "Rogério9",
    "email": "rogerio9@gmail.com",
    "nick": "rogerio",
    "address": "Rua 5",
    "num": "435",
    "complement": "Jd Manacas",
    "city": "Campinas",
    "state": "SP",
    "district": "Bairro Cidade Jd",
    "birth_date": "31-01-2000",
    "zip": "13187-232",
    "phone": "(19) 99999-9999"
}  
###
POST http://192.168.15.15:8000/api/miniatures HTTP/1.1
content-type: application/json

{   "user_id": "1",
    "brand_id": "1",
    "model": "SS",
    "color": "Vermelho",
    "description": "Opala SS Cupê 1970"
}

###

GET http://localhost:8000/api/brands HTTP/1.1

###

PUT http://localhost:8000/api/exchanges/close/1 HTTP/1.1
